import { SnakeSkinDef, FoodSkinDef, SnakeSkinId, FoodSkinId } from './game';

export const SNAKE_SKINS: Record<SnakeSkinId, SnakeSkinDef> = {
  'sumi-ink': {
    id: 'sumi-ink',
    name: 'Sumi Ink',
    tagline: 'Deep calligraphy graphite on archival drafting ground',
    headColor: '#1c2024',
    bodyColor: '#2d343b',
    tailColor: '#4f5963',
    borderColor: '#101315',
    notchColor: '#e8e5db',
    eyeWhite: '#f4f2ea',
    pupilColor: '#101214',
  },
  'moss-paper': {
    id: 'moss-paper',
    name: 'Roasted Moss',
    tagline: 'Traditional tea-leaf wash on warm textured paper',
    headColor: '#244533',
    bodyColor: '#325c44',
    tailColor: '#4b7a5d',
    borderColor: '#172e21',
    notchColor: '#f1ede1',
    eyeWhite: '#f5f3e9',
    pupilColor: '#102017',
  },
  'prussian-blueprint': {
    id: 'prussian-blueprint',
    name: 'Cyanotype Blue',
    tagline: 'Architectural drafting ink with crisp chalk registration',
    headColor: '#183454',
    bodyColor: '#264c78',
    tailColor: '#3d689c',
    borderColor: '#0f2238',
    notchColor: '#e9f1fa',
    eyeWhite: '#f0f5fc',
    pupilColor: '#0b1929',
  },
  'vermilion-terracotta': {
    id: 'vermilion-terracotta',
    name: 'Artisan Terracotta',
    tagline: 'Earthy wood-fired clay and cinnabar pigment',
    headColor: '#a63822',
    bodyColor: '#c5492f',
    tailColor: '#db674e',
    borderColor: '#7a2412',
    notchColor: '#faf3ee',
    eyeWhite: '#fdf7f3',
    pupilColor: '#4d1408',
  },
  'lead-monochrome': {
    id: 'lead-monochrome',
    name: 'Letterpress Lead',
    tagline: 'High-contrast industrial monochrome typography',
    headColor: '#121416',
    bodyColor: '#2b2d31',
    tailColor: '#4a4d53',
    borderColor: '#08090a',
    notchColor: '#f5f5f5',
    eyeWhite: '#ffffff',
    pupilColor: '#000000',
  },
};

export const FOOD_SKINS: Record<FoodSkinId, FoodSkinDef> = {
  'vermilion-pip': {
    id: 'vermilion-pip',
    name: 'Hanko Vermilion',
    tagline: 'Crisp Japanese seal stamp mark',
    fillColor: '#cf382b',
    strokeColor: '#9c2419',
    innerMarkColor: '#ffffff',
    shape: 'diamond',
  },
  'brass-ring': {
    id: 'brass-ring',
    name: 'Machined Eyelet',
    tagline: 'Turned mechanical brass washer',
    fillColor: '#b88628',
    strokeColor: '#7e5a14',
    innerMarkColor: '#1c1b18',
    shape: 'ring',
  },
  'moss-square': {
    id: 'moss-square',
    name: 'Jade Seal',
    tagline: 'Precision rotated square jade token',
    fillColor: '#275e3f',
    strokeColor: '#163b26',
    innerMarkColor: '#f3efe3',
    shape: 'square',
  },
  'bone-diamond': {
    id: 'bone-diamond',
    name: 'Drafting Marker',
    tagline: 'Ivory architectural marker with ink point',
    fillColor: '#ece9df',
    strokeColor: '#2b2e32',
    innerMarkColor: '#1a1d20',
    shape: 'pip',
  },
  'persimmon-knot': {
    id: 'persimmon-knot',
    name: 'Persimmon Knot',
    tagline: 'Warm geometric seal token',
    fillColor: '#d65b26',
    strokeColor: '#963910',
    innerMarkColor: '#fcf6ee',
    shape: 'knot',
  },
};
